# This plugin supports Chat Color with the '&' Symbol.

# Options:
# {PLAYERGETTINGHURT} is replaced with the player who is being hurt.
# {PLAYERCAUSINGHARM} is replaced with the players who is causing the harm.
