# This plugin supports Chat Color with the '&' Symbol.

# Options:
# %PLAYER% is replaced with the players name.
# This lists all the regions in all the worlds, if you decide to change any manually.
DefaultMessages:
  NoPermission: "&7[&3PvPToggle&7] &3&oYou do not have the required permissions to perform this command."
  WrongUsage: "&7[&3PvPToggle&7] &3&oIncorrect usage, use '/pvptoggle' for help."
  
# This is for the future, where logs will auto-send to me when an error is thrown. 
# Setting it to false, will of course, not send any logs to me for me to investigate.
AutomaticallySendLogs: true

# This is if you want OPs to bypass region limitations.
# Note, antibow.bypass permission will also bypass settings depending on if this setting is enabled or not.
OPsToBypass: false

Data:
  de77cc05-0f96-49e8-9b80-5744a41783c0: true